import type { Metadata } from "next";
import { Merriweather } from "next/font/google"; // Import Merriweather
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const merriweather = Merriweather({
  variable: "--font-merriweather", // Define CSS variable
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"], // Adjust weights if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={merriweather.className}>{children}</body> {/* Apply font */}
      </html>
    </ClerkProvider>
  );
}
